### ISSUE TITLE
Create list view

### ISSUE THREAD

**Issue by brianlove** [georgetown-cset/parat#10]
Create the list view showing the table of companies and stats

Partial list of subtasks:
* [x] Generate list/table view
* [x] Make add/remove columns modal do something
* [x] Add data structure for storing filter data
  * Filter data stored in URL params
* [x] Connect dropdown filters to the URL params
* [x] Connect slider filters to the URL params
* [x] Filter the data based on the current filters
* [x] Reset filters
* [ ] Link to detail views
* [ ] Ensure that table sorting uses a comparator that works for the `ai_pubs`/`ai_patents`/etc columns (they're objects that use `colDef.format` to display their aggregate value - we don't have an equivalent option available for sorting) &ndash; tracked in https://github.com/georgetown-cset/eto-ui-components/issues/270
* [ ] Adjusting slider columns leads to rapid changes in column widths; fix slider columns to a specific width (~120px) to prevent this from happening &ndash; tracked in https://github.com/georgetown-cset/eto-ui-components/issues/269
  * Partially addressed by adding a debounce between the slider change and the filters being updated, but fixing the column widths should firmly resolve this issue

**Comment by brianlove** [comment]
@jmelot @za158 Other than those listed in the mockups, which other fields in the data (either current or future) should have columns in the column selection dialog?

**Comment by za158** [comment]
I would need to look at the current full set of columns again - not sure I have the latest and greatest. Can either of you send to me or tell me where it lives in BQ?

**Comment by jmelot** [comment]
The PARAT data is in these tables: `ai_companies_visualization.{visualization_data, workforce_visualization_data,patent_visualization_data}`

**Comment by jmelot** [comment]
Relative to this mockup

<img width="635" alt="Screenshot 2023-06-16 at 2 45 04 PM" src="https://github.com/georgetown-cset/parat/assets/1252409/ca07e1a9-bf91-413e-83de-880daad30ad4">

Maybe we add cols for CV and Robotics publications, as well as AI pubs in top conferences? And then for workforce, both tt1_jobs (which we'll want to rename) and ai_jobs?

**Comment by za158** [comment]
What Jennifer said, plus:
- For all of the pubs and patents columns we should have two selectable versions: total over the period and growth over the period
- Let's try adding AI research intensity, defined as (AI pubs over the period)/(all pubs over the period) - assuming that the latter is what all_pubs in the visualization_data is
- CV and robotics patents as well as publications

**Comment by brianlove** [comment]
Closed by #19
