### ISSUE TITLE
Charts overlap with text on narrow viewports

### ISSUE THREAD

**Issue by brianlove** [georgetown-cset/parat#116]
> I'm not sure to what extent you intended to address responsiveness in this ticket. I noticed a couple weird things for narrow viewports, but if you want to make a different ticket for them, you can merge this. 
>
> 1. I started with a wide window and then dragged it to be narrower. At 485px, there was overlap between text and graphs. 
>
> ![Screenshot 2023-09-15 at 11 19 48 AM](https://github.com/georgetown-cset/parat/assets/3387590/6cfc1e4e-b60b-426d-8dc7-8afff0945c1e)
>
> 2. I refreshed the screen on this narrow viewport, and while the overlap went away, the legend for the last chart is cut off. 
>
> ![Screenshot 2023-09-15 at 11 20 39 AM](https://github.com/georgetown-cset/parat/assets/3387590/a9076b79-563e-4b3a-b571-b889fbc8e400)

_Originally posted by @niharikasingh in https://github.com/georgetown-cset/parat/pull/110#pullrequestreview-1629209921_

**Comment by brianlove** [comment]
Well this is bizarre - adjusting the width via the responsive layout view, widths that are multiples of 4 have this overlap issue, while when `width % 4 == 2` things are just fine.  If you refresh the page when it's a multiple of 4, things are initially fine (with the cases above flipped), but after a bit it reverts to the above behavior.

**Comment by jmelot** [comment]
Closed in https://github.com/georgetown-cset/parat/pull/195
