### ISSUE TITLE
Add field for sector

### ISSUE THREAD

**Issue by za158** [georgetown-cset/parat#120]
for at least the S&P and Fortune companies. @jmelot we discussed this on 9/7 (see sync notes) and agreed that the first thing to try is pulling the relevant data out of the PermID API. If that doesn't work Zach may have to pull it together manually.

**Comment by jmelot** [comment]
Which sector did you want to use?


![Image](https://github.com/georgetown-cset/parat/assets/1252409/4b0dbeae-d2fb-4300-bd81-183a285328d5)

**Comment by za158** [comment]
Economic sector. If it is easy to pull both, please also pull business sector in case we want to use that later instead/in addition.

**Comment by jmelot** [comment]
Closed via https://github.com/georgetown-cset/parat/pull/173
