### ISSUE TITLE
Integrate other metrics into list view

### ISSUE THREAD

**Issue by brianlove** [georgetown-cset/parat#121]
Beyond just the placeholders form early development

Use the spreadsheet from the "PARAT metrics" spreadsheet - add all available metrics for now, then Zach can decide if any should be removed

**Comment by brianlove** [comment]
@za158 How should things be handled if a value (like `ai_jobs` or `tt1_jobs`) is `null`?  Should they have a rank set to `"---"` like 0 (but without displaying "0")?  The particular situation that brought this up is sorting, where currently `null` values are sorted above the largest:

![parat-121-null-ai-jobs](https://github.com/georgetown-cset/parat/assets/22353962/3088129d-12ca-45e2-a7ca-326087823749)

**Comment by za158** [comment]
I think null should be treated as 0 for sorting purposes, if I understand
you correctly
---
Zachary Arnold
Analytic Lead, Emerging Technology Observatory (web <http://eto.tech> |
LinkedIn <https://www.linkedin.com/company/emerging-technology-observatory>
| Twitter <https://twitter.com/emergingtechobs>)
Center for Security and Emerging Technology
***@***.***

**Comment by brianlove** [comment]
@za158 Should nulls be displayed as a blank space, 0, "N/A", or something else?

**Comment by za158** [comment]
Is null synonymous with 0 in the data, or do other rows have a value of 0? if the latter, n/a, if the former, 0

**Comment by brianlove** [comment]
Closed by #126
