### ISSUE TITLE
Add ability to create user-defined groups of companies

### ISSUE THREAD

**Issue by brianlove** [georgetown-cset/parat#13]
Allow users to select a specific subset of companies (for example, their main competitors) to view in the list view and get aggregate metrics of.

**Comment by brianlove** [comment]
@za158 @jmelot Do we want to support only a single custom group per user, or multiple?  Should they persist across sessions?  Should the group definitions be exportable/importable (such as via a JSON file)?

**Comment by brianlove** [comment]
By "reflected in the view URL", you mean you want the individual companies contained in the group in the URL, so that the group can be bookmarked/shared?

**Comment by za158** [comment]
Yes. If I'm looking at stats for a group of companies I defined myself, I should be able to copy the URL, open it in a new window, and be looking at the same stats. Similar to how the Map of Science url reflects the full set of active filters.

**Comment by brianlove** [comment]
Closed by #62
