### ISSUE TITLE
Consider how year interval might be profitably refactored

### ISSUE THREAD

**Issue by jmelot** [georgetown-cset/parat#137]
and tell Jennifer what you want

**Comment by jmelot** [comment]
See also https://github.com/georgetown-cset/parat/issues/138

**Comment by brianlove** [comment]
@za158 What year ranges should be displayed in the detail view?  Will there be just a single span of years that we care about (for example, the most recent five full years (which would currently be 2018-2022)), or will different parts of the page display different spans of years?  If the latter, what would the spans be and what parts of the page would use which span?

**Comment by brianlove** [comment]
@jmelot See https://docs.google.com/document/d/1CUkZqI6vF4nx9Cq2g7A5NUs9y6OPaH0ABt1WDhHDmBk/edit#heading=h.8sk04fgk7jm6

**Comment by za158** [comment]
I see no reason why we would have more than one span of years in use. Which span it is depends on data coverage and is equally a @jmelot question (same question as in other ETO tools)

**Comment by jmelot** [comment]
We've considered, this is being addressed through other issues now
