### ISSUE TITLE
Figure out what data makes sense to pull out into a top-level object

### ISSUE THREAD

**Issue by jmelot** [georgetown-cset/parat#138]
e.g. year, column names, etc

**Comment by brianlove** [comment]
@jmelot See https://docs.google.com/document/d/1CUkZqI6vF4nx9Cq2g7A5NUs9y6OPaH0ABt1WDhHDmBk/edit

**Comment by jmelot** [comment]
Closed via https://github.com/georgetown-cset/parat/pull/149
