### ISSUE TITLE
Create detail view

### ISSUE THREAD

**Issue by brianlove** [georgetown-cset/parat#14]
Create the detail view for looking in-depth at the stats of a specific company

https://balsamiq-wireframes.appspot.com/?state={%22action%22:%22open%22,%22ids%22:[%221P0EYkAhfXhUtKdajwzvMM8s4br2cna8M%22],%22userId%22:%22114891180601934061243%22,%22resourceKeys%22:{}}

Partial list of subtasks:
* [ ] Modify UI Components's `<Table>`'s `columns.format` field to provide the full row as a second parameter (see https://github.com/georgetown-cset/eto-ui-components/issues/273)

**Comment by brianlove** [comment]
@jmelot @za158 For the company detail pages, what should we use to specify the company in the URL?  A few options are as follows:
* `CSET_id` &ndash; unique, but not understandable to the end user
* stock ticker &ndash; understandable to outside users, but potential for overlap unless we include the exchange (and what about cases where companies are listed on multiple exchanges?
* company name &ndash; clear and understandable, but there's potential for overlap between companies and also we'd have to deal with spaces, slashes, hyphens, etc.

**Comment by za158** [comment]
company name is probably best if feasible. Many companies will have no ticker.

**Comment by jmelot** [comment]
+1. The main issue I can think of with company name is future name changes, but I suppose when that happens we can set up a mapping between old and new names we can use to redirect the user if they try to access an old link.

**Comment by jmelot** [comment]
The potential for duplicate company names is a good point though. Maybe we could use cset_id as a suffix to differentiate. Any other ideas @za158 ?

**Comment by za158** [comment]
That's fine. Or (if easy) just automatically increment - company, company-1, company-2. I doubt many users will be going direct to company pages via the address bar so I think just do whatever's easiest and move on.

Crunchbase doesn't bother updating urls for companies that change their name, fyi.

**Comment by brianlove** [comment]
Closed by #19
