### ISSUE TITLE
Select thresholds for displaying fields in detail view

### ISSUE THREAD

**Issue by jmelot** [georgetown-cset/parat#140]
Brian will just grab whatever is available in the data, Jennifer to filter data appropriately

**Comment by brianlove** [comment]
Use separate objects in the data for patents to display in the "application areas" table, the "industry areas" table, and patents that should be in the list view but not in any table.  (so, something like `data.patents_applications`, `data.patents_industry`, and `data.patents_other`/`data.patents`)

**Comment by jmelot** [comment]
No thresholds, just top 5 patent fields in each category + all classifiers for papres

**Comment by brianlove** [comment]
🆕 New plan for the data structure:
* Keep `patents` as a single object (as it is today), but add a `type` field to indicate whether a patent row should appear in the "Top applications" table (value: `"application"`), in the "Top industries" table (value: `"industry"`), or in neither table (value: `null`)
