### ISSUE TITLE
Add partial year shading to detail view graphs

### ISSUE THREAD

**Issue by jmelot** [georgetown-cset/parat#142]

**Comment by za158** [comment]
Will need to be different for patents (longer lag)

**Comment by brianlove** [comment]
@za158 @jmelot What standard should be used for determining which years should be shaded?  Will this be hardcoded in the UI or present somewhere in the data?

**Comment by za158** [comment]
Defer to @jmelot who deals with this across the other tools. Not sure if there is a consistent standard

**Comment by brianlove** [comment]
Info/context from https://github.com/georgetown-cset/parat/issues/145#issuecomment-1766645773

> Ok @brianlove can you:
>
> 1.) Display a shaded/dashed region starting from the year at end{Article,Patent}Year and ending at the last element of the years array? In other apps we've shaded the incomplete data region when there has been a single line on the graph, or dashed it when there have been multiple lines.
>
> 2.) Update the intervals we use to display growth figures to the intervals in overall_data.json as discussed
>
> Anything else?
