### ISSUE TITLE
Add fields to articles and patents data indicating in which tables the data should be displayed

### ISSUE THREAD

**Issue by brianlove** [georgetown-cset/parat#147]
The detail view will determine which paper/patent subfields should be displayed in the "Top AI research topics", "Top application areas", and "Top industry areas" tables based on two keys in the data:

* For `articles`, the boolean **`isTopResearch`** will indicate that an articles row should be included in the "Top AI research topics" table.
* For `patents`, the **`type`** key will specify whether a row should be displayed in the "Top application areas" table (value: `"application"`), in the "Top industry areas" table (value: `"industry"`), or in neither table (value: `null`).

**Comment by jmelot** [comment]
Closed via https://github.com/georgetown-cset/parat/pull/149
