### ISSUE TITLE
Redo group membership data representation

### ISSUE THREAD

**Issue by brianlove** [georgetown-cset/parat#148]
Replace `company.in_sandp_500` and `company.in_fortune_global_500` with `company.groups.sp500` and `company.groups.global500`.

_Note: my assumption is that “global500” is sufficiently unique to distinguish the Fortune Global 500, but if it’s not this could be fortuneGlobal500 instead (but that’s starting to get longer than I’d prefer)._

**Comment by jmelot** [comment]
Closed via https://github.com/georgetown-cset/parat/pull/149
