### ISSUE TITLE
Check updated site with accessibility tools

### ISSUE THREAD

**Issue by jmelot** [georgetown-cset/parat#16]
- [x] webaim wave
- [x] google lighthouse (chrome)

**Comment by brianlove** [comment]
Lighthouse report of staging site, 2024-01-22 ([reports in Google Drive](https://drive.google.com/drive/folders/15JV7CKZWK2L6VgldFkda-AkI7xLaIw-x)):
|  | Desktop | Mobile |
|---|---|---|
| **Performance** | 74 | 64 |
| **Accessibility** | 93 | 93 |
| **Best practices** | 100 | 100 |
| **SEO** | 90 | 92 |

**Comment by jmelot** [comment]
Closed via https://github.com/georgetown-cset/parat/pull/206
