### ISSUE TITLE
Merge version2 branch into master

### ISSUE THREAD

**Issue by brianlove** [georgetown-cset/parat#163]
Merge `version1` into `master` - surely there aren't any major merge conflicts?

**Comment by brianlove** [comment]
Merged and updated the deployment and visual testing workflows to trigger on `master` in addition to `version2`.

Merge conflicts were only present in `web/raw_data/exchange_links.jsonl` and `web/tests/test_retrieve_data.py`, with the resolution in both being to accept the incoming changes from `version2`.

**Comment by jmelot** [comment]
Woooooooo!
