### ISSUE TITLE
Decide on initial download feature or lack thereof

### ISSUE THREAD

**Issue by za158** [georgetown-cset/parat#166]
Whether the PARAT user view will be downloadable - need to decide this

**Comment by jmelot** [comment]
Did we ever decide this? It wouldn't be hard to add

**Comment by brianlove** [comment]
I'm not aware of a decision being made - just need to know if we want it, and if so what form the downloads should take (JSON, CSV, etc)

**Comment by za158** [comment]
I don't remember either. Let's say, yes, the view currently available to the user should be downloadable, as CSV. Similar to list view in MoS
