### ISSUE TITLE
Don't aggregate growth columns in the summary row

### ISSUE THREAD

**Issue by brianlove** [georgetown-cset/parat#172]
The growth columns are currently aggregated by adding all the values together, just like all other sliders.  This doesn't make sense, so either remove the aggregation for these columns or use some other method (depending on @za158's preference)

<img src="https://github.com/georgetown-cset/parat/assets/22353962/5ca4ed24-1788-40cf-b68b-697b9f4cfccf" width="160px" />

**Comment by jmelot** [comment]
Closed via https://github.com/georgetown-cset/parat/pull/178
