### ISSUE TITLE
Patent applications data missing `counts` array

### ISSUE THREAD

**Issue by brianlove** [georgetown-cset/parat#174]
The `patents.ai_patents_applications` data entry is missing the `counts` array, which leads to an error throwing when you attempt to select it in the trends chart.  Either add the `counts` array and data, or indicate in some manner that this entry shouldn't be included in the fields available for the trends chart (such as `noTrends: true` or something similar).

https://github.com/georgetown-cset/parat/assets/22353962/96ca9dcb-665c-401f-8fc1-ac98fb01ae42

Derived from #170

**Comment by jmelot** [comment]
Yes, that was intentional as my understanding was we weren't going to display a trends chart for this. Rather than adding a new field for this, what do you think about just not displaying metrics that lack yearly counts?

**Comment by brianlove** [comment]
Closed by #175
