### ISSUE TITLE
Remove HTML markup from data files

### ISSUE THREAD

**Issue by brianlove** [georgetown-cset/parat#18]
The raw data files currently contain instances of HTML markup of React components (for example, the `__html` key under `full_market_links` in the example below).  This markup should be removed and replaced with just the relevant data (such as the URL), with the rendering and styling happening within the relevant components.

Example:
```
{
  ...
  "name": "Microsoft",
  "country": "United States",
  "website": "http://www.microsoft.com",
  ...
  "full_market_links": {
    "__html": "<a class='MuiTypography-root MuiLink-root MuiLink-underlineHover MuiTypography-colorPrimary' target='blank' rel='noreferrer' href='https://www.google.com/finance/quote/msft:nasdaq'>NASDAQ:MSFT</a>"
  },
  "market_list": "NASDAQ:MSFT",
  ...
}
```

**Comment by jmelot** [comment]
Closed via https://github.com/georgetown-cset/parat/pull/149
