### ISSUE TITLE
Clarify for the user that filters are present on non-selected columns

### ISSUE THREAD

**Issue by brianlove** [georgetown-cset/parat#181]
If a filter is set on a field/column but that column isn't currently being displayed, there's no clear indication (other than the URL and a smaller number of companies listed) that the filter is affecting the results.

Example: http://localhost:8550/?ai_patents=0%2C51&zz_columns=name%2Ccountry%2Cai_pubs - `ai_patents` is filtered to `[0, 51]`, but the only sign of this in the UI is that only 1542 of 1760 companies are listed.

![image](https://github.com/georgetown-cset/parat/assets/22353962/c2409cd4-6713-44cf-8f0d-8ef08a3a775d)

**Comment by brianlove** [comment]
@za158 Any thoughts/preferences on this?  I'm thinking perhaps the "Reset filters" button say something like "Reset 2 filters, "Reset filters (2)", or "Reset filters (2 active)"?

**Comment by za158** [comment]
I like the "2 active." What do you think about also changing the styling of that button when filters are active?

**Comment by jmelot** [comment]
Closed via https://github.com/georgetown-cset/parat/pull/203
