### ISSUE TITLE
Add organization to column selection modal

### ISSUE THREAD

**Issue by ngorluong** [georgetown-cset/parat#235]
The pop-up box is a little overwhelming. Can we organize by group and offer the option to select the different sub-groups after clicking "apply"? For example, 
- combine all types of patents, call it "patent categories," and show the different patent categories with the option to select all or some after user clicks on apply. This can be in the column heading, similar to the selection option for "stage," "sector," etc.
- combine all publications types; sub-group = CV, NLP, Robotics

**Comment by jmelot** [comment]
Merging with https://github.com/georgetown-cset/parat/issues/265 - see Zach's comments there as well

**Comment by jmelot** [comment]
@za158 can you please specify

**Comment by za158** [comment]
MVP is to reorganize in the following order and subheadings:

# Basic info
- Company
- Country
- Region
- Stage
- Sector

# Publications
- AI publications
- Recent AI pubs growth
- AI publication percentage
- AI publications in top conferences
- AI papers in last complete year (2022)
- CV publications
- NLP publications
- Robotics publications
- All publications
- 5-year total publications
- Citation counts

# Patents
- AI patents
- AI patents: recent growth
- AI patent percentage
- Granted AI patents
- All patents
- 5-year total patents

## Patents: AI use cases
- Agriculture
- Banking and finance
- Business
- Computing in government
- Document management and publishing
- Education
- Energy
- Entertainment
- Industry and manufacturing
- Life sciences
- Military
- Nanotechnology
- Networking
- Personal devices and computing
- Physical sciences and engineering
- Security
- Semiconductors
- Telecommunications
- Transportation

## Patents: AI applications and techniques
- Analytics and algorithms
- Computer vision
- Control
- Distributed AI
- Knowledge representation
- Language processing
- Measuring and testing
- Planning and scheduling
- Robotics
- Speech processing

# Workforce
- AI jobs
- Tech Tier 1 jobs

**Comment by za158** [comment]
It would be highly desirable to be able to collapse headings and/or have some sort of accordion type mechanism.

**Comment by brianlove** [comment]
@za158 The order of the columns in the above list is different from the current order of columns (due to both creating the patents subgroups and changing the order of AI patents/pubs vs all patents/pubs.  Is the above order how you want the columns to now appear in all contexts?  (both the column selection modal and the list view's table use the _same_ order of columns)
