### ISSUE TITLE
Consider indicating active filter/sort values more persistently/visibly

### ISSUE THREAD

**Issue by za158** [georgetown-cset/parat#241]
<img width="1298" alt="image" src="https://github.com/georgetown-cset/parat/assets/58824955/1c630961-e8d9-4c70-b33b-26e48ff031b4">

I find it difficult/annoying to have to look at the tooltip that comes up when a filter is active in order to see what my current settings are. I also think active sort order should be spelled out for the user.

I would put all this in text in the interface rather than under a tooltip.

**Comment by brianlove** [comment]
@za158 Are you wanting the "X filters active" text moved to the left, like the following screenshot, or are you wanting the full descriptive text of the active filters to be shown in those circled areas?

![image](https://github.com/georgetown-cset/parat/assets/22353962/ffff1fc7-2c88-4beb-9534-a6b842e9a7fe)

If the latter, I'm quite hesitant, as that will get very crowded and confusing quite quickly.  The original intent of the "X active" text in the button bar was to remind the user in the case where they have active filters on non-displayed columns.

**Comment by za158** [comment]
I think what you propose in the screenshot would work (and keep the question mark tooltip that's currently in the interface, too). So 

Viewing X of Y companies (Z filters active) (?)                X Reset filters

**Comment by brianlove** [comment]
@za158 Should I keep the "Z active" part in the reset filters button, or is that text duplicative with the new text on the left? 

The new "Z filters active" text does trigger the same tooltip as the previous '?' icon, but I can definitely add that icon back into the text

**Comment by za158** [comment]
Cut it from the reset filters button
