### ISSUE TITLE
Region

### ISSUE THREAD

**Issue by ngorluong** [georgetown-cset/parat#242]
Pull Middle Eastern countries out of Asia into its own regional group

**Comment by jmelot** [comment]
@za158 I am planning to use this list of countries as "the Middle East" - any objections? https://en.wikipedia.org/wiki/List_of_Middle_Eastern_countries_by_population

**Comment by za158** [comment]
whatever
---
Zachary Arnold
Analytic Lead, Emerging Technology Observatory (web <http://eto.tech> |
LinkedIn <https://www.linkedin.com/company/emerging-technology-observatory>
| Substack <http://etoblog.substack.com>)
Center for Security and Emerging Technology
***@***.***

**Comment by jmelot** [comment]
Closed via https://github.com/georgetown-cset/parat/pull/379
