### ISSUE TITLE
Capitalization of USAA

### ISSUE THREAD

**Issue by brianlove** [georgetown-cset/parat#244]
[USAA](https://en.wikipedia.org/wiki/USAA?useskin=vector)'s name is incorrectly capitalized:

![image](https://github.com/georgetown-cset/parat/assets/22353962/ae491601-e7f0-4fc9-b6de-d984de7df30c)

**Comment by jmelot** [comment]
Subsumed by https://github.com/georgetown-cset/parat/issues/295
