### ISSUE TITLE
Should we incorporate our gathered job info into our startup/growth/mature definition?

### ISSUE THREAD

**Issue by rggelles** [georgetown-cset/parat#245]
I notice that the largest startup has over 250 tt1 jobs. That doesn't sound super startup-y anymore, but I guess by the other criteria we're using it's still a startup. Should we add in a cutoff for this?

**Comment by za158** [comment]
Absolutely not
---
Zachary Arnold
Analytic Lead, Emerging Technology Observatory (web <http://eto.tech> |
LinkedIn <https://www.linkedin.com/company/emerging-technology-observatory>
| Substack <http://etoblog.substack.com>)
Center for Security and Emerging Technology
***@***.***

**Comment by za158** [comment]
(less brusque context: the sector designations are handwavy inherently, I'd prefer to keep them that way rather than trying to integrate quantitative metrics)

**Comment by rggelles** [comment]
Sounds fine to me! Closing this in that case.
