### ISSUE TITLE
Orgs are missing descriptions

### ISSUE THREAD

**Issue by za158** [georgetown-cset/parat#248]
eg 
<img width="1272" alt="image" src="https://github.com/georgetown-cset/parat/assets/58824955/0a09a7b1-f306-42a9-96ec-e401fa03bed6">

**Comment by ngorluong** [comment]
Companies with no wikipedia page don't have descriptions. Consider pulling those from other sources like Crunchbase.

**Comment by jmelot** [comment]
obe, addressed via pulling from airtable
