### ISSUE TITLE
Apollo's website is listed as verizon.com

### ISSUE THREAD

**Issue by za158** [georgetown-cset/parat#251]
<img width="1272" alt="image" src="https://github.com/georgetown-cset/parat/assets/58824955/04102d14-6af3-434f-a6c7-d71461e711ed">

**Comment by jmelot** [comment]
Obe... this org is no longer in Parat

**Comment by za158** [comment]
💪
---
Zachary Arnold
Analytic Lead, Emerging Technology Observatory (web <http://eto.tech> |
LinkedIn <https://www.linkedin.com/company/emerging-technology-observatory>
| Substack <http://etoblog.substack.com>)
Center for Security and Emerging Technology
***@***.***
