### ISSUE TITLE
NaN% in detail view table

### ISSUE THREAD

**Issue by niharikasingh** [georgetown-cset/parat#254]
I found a "NaN%" for Dahua Technology. 

<img width="393" alt="Screenshot 2024-03-19 at 2 34 28 PM" src="https://github.com/georgetown-cset/parat/assets/3387590/ee0db4fa-fd6d-435e-be34-6110ca0bde48">

**Comment by jmelot** [comment]
@brianlove I'll take a look to see if this is coming from my stuff or yours and reassign to you if needed
