### ISSUE TITLE
If 2022 has incomplete data, then the 2021-22 line should be gray

### ISSUE THREAD

**Issue by brianlove** [georgetown-cset/parat#262]
I'm not sure if the 2022 data is complete or incomplete, but if it's incomplete, the line between 2021 and 2022 should probably be gray (with a colored dot for 2021 presuming that year is complete).  Basically, colored dots and lines up until and including the final year of complete data, then start with a gray line for the rest.

![image](https://github.com/georgetown-cset/parat/assets/22353962/7cead4b5-992c-4798-ac33-3e56d1372473)

(If 2022 is complete, then that dot should be colored)

**Comment by jmelot** [comment]
Subsumed by https://github.com/georgetown-cset/parat/issues/295

**Comment by jmelot** [comment]
I will ponder and then reassign to you

**Comment by jmelot** [comment]
Let's color the dot, 2022 should be complete
