### ISSUE TITLE
Add organization to filter selection dialog

### ISSUE THREAD

**Issue by za158** [georgetown-cset/parat#265]
The flat list we currently have is too overwhelming. Need subheadings (Basic information, AI Publications, AI Patents, AI Workforce) and/or other visual cues to indicate structure.

<img width="485" alt="image" src="https://github.com/georgetown-cset/parat/assets/58824955/458c347a-061c-4a95-a496-7b1fcb06b3c5">

**Comment by jmelot** [comment]
Duplicate-ish of https://github.com/georgetown-cset/parat/issues/235
