### ISSUE TITLE
Citation counts field isn't clear

### ISSUE THREAD

**Issue by rggelles** [georgetown-cset/parat#266]
Without a tooltip or a clearer name, it's not clear if we're talking about citation counts of all papers or citation counts of AI papers. As it is, since it comes after all publications in the drop-down list, I'd probably infer the former.

**Comment by jmelot** [comment]
I will confirm the metric and then hand off to Zach/Brian for updating wording

**Comment by za158** [comment]
I'm going to be doing a bulk renaming/conforming to the documentation, will
address this
---
Zachary Arnold
Analytic Lead, Emerging Technology Observatory (web <http://eto.tech> |
LinkedIn <https://www.linkedin.com/company/emerging-technology-observatory>
| Substack <http://etoblog.substack.com>)
Center for Security and Emerging Technology
***@***.***
