### ISSUE TITLE
Add tooltip next to every country group in dropdown

### ISSUE THREAD

**Issue by za158** [georgetown-cset/parat#269]
<img width="326" alt="image" src="https://github.com/georgetown-cset/parat/assets/58824955/600e81e2-070b-494d-bbb8-d69f4db10e01">

**Comment by brianlove** [comment]
@za158 Is there specific content that you have in mind for the Fortune Global 500 group's tooltip?  Right now, the S&P 500 tooltip is primarily focused on explaining why it doesn't have 500 companies (an issue that Fortune doesn't have), so the only part that seems applicable to me is the last sentence:

> PARAT may not list exactly 500 companies for this group:
> 
> * S&P 500 membership changes over time, and so PARAT includes all companies that were present on the list at some point in 2020. This can increase the number of listed companies.
> * Companies that were acquired during the data period will be listed under the acquiring company, even if that company is not itself on the S&P 500. This can reduce the number of listed companies.
>
> For more information, review [our documentation](https://eto.tech/tool-docs/parat#SOME_METHODOLOGY_SECTION).
