### ISSUE TITLE
Make it clearer what the background line indicates

### ISSUE THREAD

**Issue by jmelot** [georgetown-cset/parat#271]
Might not be obvious to a user that it's an average

<img width="809" alt="Screenshot 2024-03-19 at 2 41 26 PM" src="https://github.com/georgetown-cset/parat/assets/1252409/88d207ec-38a7-498a-be28-8eb236db7193">

**Comment by jmelot** [comment]
See also: https://github.com/georgetown-cset/parat/issues/255

**Comment by jmelot** [comment]
Do either of you object if we just change the label for the group to "Average Fortune Global 500"?

**Comment by brianlove** [comment]
Works for me.  I'm going back and forth in my head about whether "Average Fortune Global 500", "Average of Fortune Global 500", or "Fortune Global 500 average" are the best phrasing, but don't want to get into bikeshedding.

**Comment by za158** [comment]
Fortune Global 500 (average)

**Comment by za158** [comment]
also, unlikely we're launching with the global 500 (I know that's not the point here)
