### ISSUE TITLE
Table rows don't have separator line

### ISSUE THREAD

**Issue by niharikasingh** [georgetown-cset/parat#283]
[iPad 10, iOS 16, chrome]

See the last two rows here. I couldn't get the URL off browserstack, but 3/4 of the filters are shown here, and the other one is the slider to the right of "AI publications" 

<img width="524" alt="Screenshot 2024-03-19 at 2 53 34 PM" src="https://github.com/georgetown-cset/parat/assets/3387590/2c31f108-d1f6-4901-b064-ac4c753fd704">

**Comment by brianlove** [comment]
This appears to be a Safari bug - Firefox and Chrome show the border just fine, but Safari does not.
