### ISSUE TITLE
Google v Alphabet

### ISSUE THREAD

**Issue by billsponsor** [georgetown-cset/parat#284]
<img width="1341" alt="Screenshot 2024-03-19 at 2 53 28 PM" src="https://github.com/georgetown-cset/parat/assets/39040541/4be279c7-16ca-49e9-97a1-be5bb6582314">

How to handle Alphabet vs Google? Ex. is Alphabet (not Google) actually linked to 151 AI publications that are not tied to Google?

**Comment by brianlove** [comment]
If we add some sort of text in Alphabet's name to specify that it does not include Google (example: "_Alphabet (except Google)_"), then that'll need to be a new data value that is distinct from the company name used in the slug generation and detail page (perhaps `displayName` in addition to the current `name`?)

**Comment by jmelot** [comment]
Reassign to me if you need me to do something after Zach takes a look

**Comment by brianlove** [comment]
The company name is currently used in several places:
* The 'Company' column in the list view table
* The title of the detail page
* The URL slug of the detail page

If we're adding "including Google" to the table and/or title instances, we will still want that to come from the `displayName` property in the company records unless we are absolutely sure that we want the "including Google" bit to be included in all of those places (for example, the URL slug being `/company/796-alphabet-including-google`).

**Comment by za158** [comment]
subsumes #325
