### ISSUE TITLE
Expand Descriptions 

### ISSUE THREAD

**Issue by billsponsor** [georgetown-cset/parat#291]
<img width="1393" alt="Screenshot 2024-03-19 at 2 57 56 PM" src="https://github.com/georgetown-cset/parat/assets/39040541/63c54afd-eb63-4fed-af7d-82d5adf0689c">

https://en.wikipedia.org/wiki/State_Grid_Corporation_of_China

Either ["company name + country"] or [website name minus suffix + wikipedia] could surface wikipedia entry.

**Comment by jmelot** [comment]
OBE, closed via pulling from airtable + updating descriptions there
