### ISSUE TITLE
Consider making it clearer that most of the metrics in the patents panel are for applications

### ISSUE THREAD

**Issue by jmelot** [georgetown-cset/parat#292]
I feel like this isn't super clear right now

**Comment by brianlove** [comment]
Based on my review, I think you're referring to the following possible changes:
* [ ] "#X in PARAT for number of AI-related" -> "...number of AI-related patent applications"
* [ ] "X% growth in COMPANY's AI patenting" -> "...AI patent applications"
* [ ] "X% of COMPANY's total patenting was AI-focused" -> "...total patent applications were AI-focused"
* [ ] Heading "Trends in COMPANY's patenting in TOPIC" -> "...in COMPANY's patent applications..."

@jmelot @za158 Are these correct?  Am I missing any?

**Comment by rggelles** [comment]
So, this isn't quite accurate.

The metrics are for applications *and* grants. They just don't *exclude* applications. Other than that, this looks right.

**Comment by brianlove** [comment]
@za158 Based on Rebecca's feedback, what would be your preferred phrasing in these places?

**Comment by za158** [comment]
I am honestly not sure what this issue is about - @jmelot what did you have in mind here exactly

**Comment by jmelot** [comment]
@za158 I just thought that some of the wording in this panel - for example "X% growth in COMPANY's AI patenting" - suggests we're talking about granted patents when we aren't. Maybe this is just me though... Screenshot to remind us of the current state of things

<img width="833" alt="Screenshot 2024-05-14 at 5 20 00 PM" src="https://github.com/georgetown-cset/parat/assets/1252409/ccdec7ec-8687-41cc-982e-79d4314a1ce7">

**Comment by jmelot** [comment]
I do realize the "obtained" issue is being dealt with here https://github.com/georgetown-cset/parat/issues/339

**Comment by za158** [comment]
Ah. I see. I will tweak some other bits of the screenshotted text consistent with #339
