### ISSUE TITLE
Fallback content missing from list view

### ISSUE THREAD

**Issue by brianlove** [georgetown-cset/parat#332]
When the group selection interface was reworked, it turns out that I removed the `fallbackContent` prop entirely, not just the group selection-specific portions: https://github.com/georgetown-cset/parat/pull/156/files#diff-ba3697f91a401bfa286b097d160a1077235f101ee783cbe1b201838d52d6ea11L554  I don't remember (and didn't find) any mentions about intending for the fallback content to be removed.

Assuming that we still want fallback content, there are a still issues that will need to be resolved:
* If a group is selected, its row is considered to be a result, and so even if there are no actual companies in the results, no fallback content is displayed
  * This probably requires a change to `<Table>` to trigger when `fallbackContent` displays
  * Alternatively, if the only data rows would be groups, then maybe filter it out so that there truly are no results in this case (would likely require no changes to UIC)
* There seem to be (more 😭) table border issues with the header rows and summary footer rows in these cases.

@za158 Should the fallback content be re-added to PARAT?  Mockup below:

| Existing | With fallback content |
| --- | --- |
| ![image](https://github.com/georgetown-cset/parat/assets/22353962/36ec6c85-a2d9-4220-a5ef-bd6288132c79) | ![image](https://github.com/georgetown-cset/parat/assets/22353962/bc1c5225-bedb-4993-9814-8a745ab4d65d) |

**Comment by za158** [comment]
I much prefer "With fallback content"
