### ISSUE TITLE
Add incomplete interval labels to graphs

### ISSUE THREAD

**Issue by za158** [georgetown-cset/parat#336]
![image](https://github.com/georgetown-cset/parat/assets/58824955/6c5110ff-821f-4e21-9e67-1e841d4d168c)

**Comment by jmelot** [comment]
Something like what we do in MoS?

<img width="560" alt="Screenshot 2024-05-14 at 1 38 23 PM" src="https://github.com/georgetown-cset/parat/assets/1252409/1025529b-5760-4904-b380-d037b47be522">

**Comment by za158** [comment]
Ya
