### ISSUE TITLE
Rework patent dropdown in detail view

### ISSUE THREAD

**Issue by za158** [georgetown-cset/parat#337]
![image](https://github.com/georgetown-cset/parat/assets/58824955/bfc28d38-afad-43ef-8e7b-134f17142dc4)

- needs organization into subgroups, or
- restrict display to selected categories
- "AI recent growth"? "AI"?

**Comment by brianlove** [comment]
@za158 What subcategories should exist and what entries should appear in which?

**Comment by za158** [comment]
Acknowledging receipt, I will answer next week

**Comment by za158** [comment]
The dropdown should display "AI (all)", then list the applications categories under a subheading, then ditto industry areas. Anything that is not part of one of those buckets should be removed from the dropdown.

https://github.com/georgetown-cset/1790-ai-patent-data/blob/master/Functional_Application_Categories.md - applications
https://github.com/georgetown-cset/1790-ai-patent-data/blob/master/Application_Fields_Categories.md - industries
