### ISSUE TITLE
Multiple patents data fields with no trends data

### ISSUE THREAD

**Issue by brianlove** [georgetown-cset/parat#357]
Several entries in the `patents` data object do not contain data in `counts`, leading to empty charts displaying in the "_Trends in [COMPANY]'s patenting in [SUBJECT]_" charts:
* "5-year total" (key `all_patents_5yr`)
* "Granted AI" (key `ai_patents_grants`)
* "AI patent percentage" (key `ai_patents_percent`)
* "AI recent growth" (key `ai_patents_growth`)

![image](https://github.com/georgetown-cset/parat/assets/22353962/29db5399-347c-486d-9e45-2f30b605e03c)

Are these fields expected to have data (now or before release), or should they be hidden from the trends dropdown?

**Comment by brianlove** [comment]
This might be resolved by https://github.com/georgetown-cset/parat/issues/337

**Comment by jmelot** [comment]
reassigning to you since you closed it!
