### ISSUE TITLE
Revisit orgs to not roll up

### ISSUE THREAD

**Issue by jmelot** [georgetown-cset/parat#375]
Here is the line that specifies the orgs to not roll up (these are legacy CSET ids)

https://github.com/georgetown-cset/parat/blob/master/company_linkage/parat_scripts/aggregate_organizations.py#L11

Can you check and see if you want to make any modifications to this list? I already removed google

**Comment by za158** [comment]
Let's get rid of all of these. They largely don't matter/are OBE at this point. And that will simplify the explanation
