### ISSUE TITLE
Investigate orgs with null names

### ISSUE THREAD

**Issue by jmelot** [georgetown-cset/parat#376]
I noticed that CSET ids 802 and 617 have null names in `high_resolution_entities.aggregated_organizations` but not in `high_resolution_entities.organizations`. Do you have any ideas why that might be the case, and if so could you please check? If not feel free to reassign to me

**Comment by rggelles** [comment]
No, I have no idea. I checked them in the raw data and neither of them have parents, which is the only reason their name would be reassigned in aggregate_organizations. If the name is being correctly pulled in organizations, it should work in aggregated_organizations too.
