### ISSUE TITLE
only S&P 500 as a comparator in graphs

### ISSUE THREAD

**Issue by za158** [georgetown-cset/parat#392]
![image](https://github.com/georgetown-cset/parat/assets/58824955/a512f291-9557-4d41-b296-99822f521d16)

For now let's only include S&P 500. No other groups (existing now or forthcoming) should be included in these graphs.

**Comment by brianlove** [comment]
@za158 This is the case for _all_ graphs on the detail view page, right?  Not just the one in the screenshot?

**Comment by za158** [comment]
Yes
