### ISSUE TITLE
Un-capitalization of names

### ISSUE THREAD

**Issue by za158** [georgetown-cset/parat#407]
OpenAI appears as "Openai" in the interface. Why is this? It's correct in Airtable

![image](https://github.com/georgetown-cset/parat/assets/58824955/bbc73edb-5869-4575-95b9-48a6141bb128)

**Comment by brianlove** [comment]
This is an issue with the underlying data, so reassigning to @jmelot 

<img width="377" alt="image" src="https://github.com/georgetown-cset/parat/assets/22353962/e5d67f7a-0f42-4e1a-8f0c-3e0908981692">

GraphQL:
<img src="https://github.com/georgetown-cset/parat/assets/22353962/22b0d22f-19fa-4c64-913a-f19d88261680" width="240">
