### ISSUE TITLE
Highly cited articles

### ISSUE THREAD

**Issue by za158** [georgetown-cset/parat#411]
![image](https://github.com/georgetown-cset/parat/assets/58824955/3aa9991d-2521-4c42-9cec-d857e08ec1bd)

1. How is highly cited defined? Is it the same as in MoS (top 10% in each publication year)?
2. This value is not currently available as a column in the main view. Can it become a column there? Will need to make conforming changes to documentation, tooltip files, etc.

**Comment by rggelles** [comment]
Yes, highly cited is top 10% in each publication year.

**Comment by za158** [comment]
Neat thank you
---
Zachary Arnold
Analytic Lead, Emerging Technology Observatory (web <http://eto.tech> |
LinkedIn <https://www.linkedin.com/company/emerging-technology-observatory>
| Substack <http://etoblog.substack.com>)
Center for Security and Emerging Technology
***@***.***

**Comment by brianlove** [comment]
@za158 Where would you like the "highly-cited articles" column to fit amongst the other columns?

**Comment by za158** [comment]
@rggelles double-checking, these are highly cited AI articles specifically, yes?

**Comment by brianlove** [comment]
@za158 The data key is `highly_cited_ai_pubs`, so presumably yes
