### ISSUE TITLE
Revise credits block

### ISSUE THREAD

**Issue by za158** [georgetown-cset/parat#441]
![image](https://github.com/georgetown-cset/parat/assets/58824955/07780c86-f08a-4c47-afad-02f41328851c)

I can't easily find where to edit this text (is it a shared component?). For PARAT, I would like it to read as follows:

`The AI activity metrics in the <ExternalLink href="/dataset-docs/private-sector-ai-indicators/">Private-Sector AI Indicators dataset</ExternalLink> are derived from data from <ExternalLink href="https://www.reveliolabs.com/">Revelio Labs</ExternalLink>, <ExternalLink href="https://clarivate.com/products/scientific-and-academic-research/research-discovery-and-workflow-solutions/webofscience-platform/">Clarivate Web of Science</ExternalLink>, and other leading sources. Additional descriptive metadata in PARAT comes from the <ExternalLink href="https://data.crunchbase.com/v3.1/docs/open-data-map">Crunchbase Open Data Map</ExternalLink> (<ExternalLink href="https://crunchbase.com">powered by Crunchbase</ExternalLink>) and <ExternalLink href="https://permid.org/">PermID</ExternalLink>. For details on our sourcing...` [complete sentence as it currently exists but update link to PARAT documentation specifically]

**Comment by jmelot** [comment]
Brian I hackily did this through a custom component (we had to have this done today so we could give someone a preview). Feel free to improve later
