### ISSUE TITLE
Percentage symbols missing from detail view tables

### ISSUE THREAD

**Issue by za158** [georgetown-cset/parat#459]
![image](https://github.com/georgetown-cset/eto-platform/assets/58824955/f1e96631-6da4-48a8-973f-b3adce7d29af)

**Comment by brianlove** [comment]
@za158 Should these columns (growth and patents filed) be right-justified (since they're numbers)?

**Comment by za158** [comment]
For all my fussing, justification of numbers is something I have genuinely never cared about. I'd leave as is.
