### ISSUE TITLE
More pubs in AI than overall for id 183

### ISSUE THREAD

**Issue by jmelot** [georgetown-cset/parat#46]
In 2019, from

```SELECT all_pubs_by_year, ai_pubs_by_year FROM ai_companies_visualization.visualization_data where cset_id = 183```

With all the merged corpus updates I can imagine that this might be due to some kind of discrepancy there or something, we can take another look after the data is updated, just making a note of it now so I don't forget

**Comment by rggelles** [comment]
This did not persist. Closing.
