### ISSUE TITLE
Invalid "GER" country

### ISSUE THREAD

**Issue by jmelot** [georgetown-cset/parat#47]
pycountry doesn't understand "GER" (see: `SELECT * FROM ai_companies_visualization.visualization_data where country = "GER"`). Eyeballing the data, I'm guessing this is Germany - I can add a special case to convert this if that's correct

**Comment by rggelles** [comment]
I can fix this in the new version pretty easily now that we can auto-migrate things from Airtable; I'll just update the country for these.
