### ISSUE TITLE
List view buttons are still weird in safari

### ISSUE THREAD

**Issue by jmelot** [georgetown-cset/parat#470]
This seems to only be triggered after window resize

![Screenshot 2024-06-26 at 10 42 35 AM](https://github.com/georgetown-cset/parat/assets/1252409/63c84338-2a19-491f-948f-a9a61fb49b6c)

**Comment by brianlove** [comment]
This seems to be a bug with Safari, with the browser not properly resizing elements when the window is resized.  I tried a few things to try to manually trigger reflow from https://gist.github.com/paulirish/5d52fb081b3570c81e3a, but had no luck.  Firefox and Chrome don't have this issue, so as far as I'm concerned, it's on Apple to fix their browser (plus things work correctly when the page is loaded, so it wouldn't affect those platforms that are forced to use Safari).
