### ISSUE TITLE
Ensure consistent spacing of numbers and ranks

### ISSUE THREAD

**Issue by jmelot** [georgetown-cset/parat#56]
Right now they don't line up

<img width="160" alt="Screenshot 2023-08-22 at 10 27 16 AM" src="https://github.com/georgetown-cset/parat/assets/1252409/23c621b1-be10-4824-92fb-911a66b73635">

**Comment by brianlove** [comment]
@za158 @jmelot Here's the current layout of the numbers and rankings - should there be any additional adjustments to the layout?

<img src="https://github.com/georgetown-cset/parat/assets/22353962/f637865e-5fec-4e03-877e-d03338f60da4" width="400" />

**Comment by za158** [comment]
Looks alright to me

**Comment by brianlove** [comment]
Resolved by a3914f2 (#65)
