### ISSUE TITLE
Reset selected page on filter change

### ISSUE THREAD

**Issue by jmelot** [georgetown-cset/parat#57]
Right now if you navigate a few pages in, then change your filter values such that fewer results are returned than the number needed to populate the page you're on, you see stuff like this:

<img width="1792" alt="Screenshot 2023-08-22 at 10 25 59 AM" src="https://github.com/georgetown-cset/parat/assets/1252409/cd2d2464-b10d-4541-8ffe-fdcb1e9be066">

**Comment by brianlove** [comment]
This requires an adjustment to `<Table>`, tracked in https://github.com/georgetown-cset/eto-ui-components/issues/339

**Comment by brianlove** [comment]
Look into how MoS does this - the page state is reset when filters are adjusted there

**Comment by brianlove** [comment]
Closed by #204
