### ISSUE TITLE
Determine how/where "Yearly citations" should be presented on detail page

### ISSUE THREAD

**Issue by brianlove** [georgetown-cset/parat#58]
The data update in #41 adds `articles.citation_counts` (aka "Yearly citations") to the data for each company, but it isn't clear to me where the best place for these data would be.  My current thought is to add another chart for this (probably after conference pubs), but I figured I'd see if there was another idea/preference for these data.

![parat-41--full-detail-page-with-charts](https://github.com/georgetown-cset/parat/assets/22353962/34c0e204-3eb4-4573-9035-cfb88069c98e)

**Comment by za158** [comment]
I don't think we need a whole chart for it especially since variation over time will not be interesting in most cases. I'd suggest a single-number callout (as in workforce) for average citations per article.

**Comment by jmelot** [comment]
Agreed. Does that make sense to you as well @brianlove ?

**Comment by za158** [comment]
We could give a citations-per-article rank relative to some reasonable
cohort, at least for big companies. Or (probably easier) total citations to
their AI articles
---
Zachary Arnold
Analytic Lead, Emerging Technology Observatory (web <http://eto.tech> |
LinkedIn <https://www.linkedin.com/company/emerging-technology-observatory>
| Twitter <https://twitter.com/emergingtechobs>)
Center for Security and Emerging Technology
***@***.***

**Comment by jmelot** [comment]
@brianlove do you have what you need here?

**Comment by jmelot** [comment]
I'm going to close it but feel free to open back up if you need more input!
