### ISSUE TITLE
Revise company details table in detail view and add popup

### ISSUE THREAD

**Issue by za158** [georgetown-cset/parat#81]
![image](https://github.com/georgetown-cset/parat/assets/58824955/2250d0c3-a430-40eb-a860-20d0fd6ffe49)

This table should include country, sector (), website, and a field that includes market_filt if present and is hidden if not.

It should also include a "View more details" link to a popup or hidden pane which displays the following repeated/additional metadata in this order (refer to https://docs.google.com/spreadsheets/d/1qSaJ1IZ1xm4tkELeoOMxjBMb0Y40eGAKnBzGXPBhQCQ/edit#gid=0):

name
aliases
parent_info
country
continent
website
crunchbase.crunchbase_url
child_crunchbase
linkedin
in_sandp_500
in_fortune_global_500
stage
full_market_links

**Comment by brianlove** [comment]
@za158 Couple questions:

1. What field is "sector" listed in - I'm not seeing that field in the data and haven't found/noticed another field that seems equivalent
2. Is the list that you gave (country, sector, website, market_filt, and "view more") the exhaustive list of what should be in that table, or just additional fields to ensure are present (i.e. should I just add those, or also remove aliases, region, and stage, which are currently present)

**Comment by za158** [comment]
1. "Sector" doesn't exist yet - we need to add that field. See #120 which I just made. For now dummy data are fine (not sure whether adding the field in the first place is a @jmelot task or a @brianlove task)

2. It is exhaustive. The fields you mentioned should appear only in the popup I mentioned.

**Comment by brianlove** [comment]
Closed by #129
