### ISSUE TITLE
Detail view nav menu doesn't move with scroll

### ISSUE THREAD

**Issue by za158** [georgetown-cset/parat#82]
![image](https://github.com/georgetown-cset/parat/assets/58824955/9b818caa-623a-44ec-abe2-2798a4b8c65f)
![image](https://github.com/georgetown-cset/parat/assets/58824955/90abab55-2a50-4427-84c9-3d388b5c5323)

**Comment by brianlove** [comment]
This was resolved in #73 (commit d41657e)
