### ISSUE TITLE
Add comparison lines in detail view graphs to S&P 500/Fortune Global 500

### ISSUE THREAD

**Issue by za158** [georgetown-cset/parat#84]
If a company is in those groups, add an additional comparison line in each graph with the average for the group. So Microsoft's graphs should have a line in them for the S&P 500 average, for example.

**Comment by brianlove** [comment]
The underlying data needed for this and #101 seem to be the same (at least from my current understanding)

**Comment by brianlove** [comment]
Closed by #170 and #169
