### ISSUE TITLE
Add subfield table to "all AI" view in pubs and patents

### ISSUE THREAD

**Issue by za158** [georgetown-cset/parat#86]
Notwithstanding #85, a table should appear with stats for the different subfields we track (columns - subfield: number of papers:growth in papers over 5 year period:citations per paper)

**Comment by jmelot** [comment]
We don't currently have the yearly counts for fields that would allow us to calculate growth. Just looking at the field counts for e.g. Alphabet right now, the numbers are so low I don't expect the growth numbers to be meaningful (these are level 2 fields)

**Comment by za158** [comment]
If that's the case, we could omit from this table. (We're not talking about the overall "all AI papers" growth number for each company, yes?)

**Comment by jmelot** [comment]
Yeah, I'm talking about the publication subfields. We _do_ have yearly counts for patent fields

**Comment by brianlove** [comment]
The tables are present on the detail page, but they currently show only placeholder data pending https://github.com/georgetown-cset/parat/issues/147 and other data updates.

**Comment by brianlove** [comment]
This looks to be complete now (per Brian/Jennifer meeting)
