### ISSUE TITLE
Consider explanatory/elaborating text laid out alongside pullouts

### ISSUE THREAD

**Issue by za158** [georgetown-cset/parat#89]
I am inclined to do something like this, where the Lorem ipsum text would potentially include additional derived statistics (see bolding first line as an example). Is this offensive to other people? @jmelot @brianlove 

If we do this I can provide the exact text/additional stats desired

![image](https://github.com/georgetown-cset/parat/assets/58824955/a20539c0-f292-4887-9fbb-af80cb2e7863)

**Comment by brianlove** [comment]
👍  Looks good to me!

**Comment by za158** [comment]
See comment in mockup on this
![image](https://github.com/georgetown-cset/parat/assets/58824955/187f634e-e04d-4dd4-97e6-cc941b83fb0d)

**Comment by jmelot** [comment]
Yeah I think this looks nice

**Comment by brianlove** [comment]
@za158 Do you consider this fully or only partially implemented now that #133 has been merged?

**Comment by za158** [comment]
Fully; or, in any event, it will have been fully implemented as detail view mockup is (ie no need for this issue to exist independently any longer)
