### ISSUE TITLE
add display 20, 50, 100 option to pagination

### ISSUE THREAD

**Issue by za158** [georgetown-cset/parat#93]
![image](https://github.com/georgetown-cset/parat/assets/58824955/0aeb4f6d-bec4-446a-8f7c-d07bf74ef9e1)

**Comment by brianlove** [comment]
This depends on https://github.com/georgetown-cset/eto-ui-components/issues/324

**Comment by jmelot** [comment]
We're unblocked from this now, right?

**Comment by za158** [comment]
Yes
---
Zachary Arnold
Analytic Lead, Emerging Technology Observatory (web <http://eto.tech> |
LinkedIn <https://www.linkedin.com/company/emerging-technology-observatory>
| Substack <http://etoblog.substack.com>)
Center for Security and Emerging Technology
***@***.***

**Comment by brianlove** [comment]
Closed by #204
