### ISSUE TITLE
Implement download button

### ISSUE THREAD

**Issue by za158** [georgetown-cset/parat#96]
Right now it’s always gray. When do we intend it to trigger?

**Comment by brianlove** [comment]
Currently it's just a (disabled) placeholder that I added early in development.  Functionality will be coming at some point - any info regarding the nature of the downloads would be appreciated.

**Comment by brianlove** [comment]
The fate of the 'Download' button will be determined by #166.  Depending on the results, this button may get a purpose in life, or it may be removed.

**Comment by jmelot** [comment]
Per https://github.com/georgetown-cset/parat/issues/166#issuecomment-1877979213 we'll implement

**Comment by brianlove** [comment]
Closed by #194
